const dummy_products = [
  {
    id: "1",
    name: "Product A",
    price: 499,
    availability: true,
    quantity: 10,
    image: "https://picsum.photos/150?random=1",
    category: "Electronics",
  },
  {
    id: "2",
    name: "Product B",
    price: 799,
    availability: false,
    quantity: 3,
    image: "https://picsum.photos/150?random=2",
    category: "Home Appliances",
  },
  {
    id: "3",
    name: "Product C",
    price: 299,
    availability: true,
    quantity: 20,
    image: "https://picsum.photos/150?random=3",
    category: "Books",
  },
  {
    id: "4",
    name: "Product D",
    price: 1299,
    availability: true,
    quantity: 5,
    image: "https://picsum.photos/150?random=4",
    category: "Clothing",
  },
  {
    id: "5",
    name: "Product E",
    price: 999,
    availability: true,
    quantity: 15,
    image: "https://picsum.photos/150?random=5",
    category: "Sports",
  },
  {
    id: "6",
    name: "Product F",
    price: 1499,
    availability: true,
    quantity: 7,
    image: "https://picsum.photos/150?random=6",
    category: "Toys",
  },
  {
    id: "7",
    name: "Product G",
    price: 349,
    availability: false,
    quantity: 1,
    image: "https://picsum.photos/150?random=7",
    category: "Stationery",
  },
];

export default dummy_products;
