export const API_URLS ={
    ADMIN_LOGIN: '/api/admin/user/login',
    GET_CATEGORIES: '/api/category',
    GET_SUB_CATEGORIES: '/api/sub-categories',
    PRODUCT_SLUG_CHECKER: '/api/product/slug-checker',
    PRODUCT: '/api/product',
    PRODUCT_SEARCH: '/api/product/search',
    PRODUCT_CATEGORY: '/api/product/category',
    USER_LOGIN: '/api/user/login',
    USER_SIGNUP: '/api/user/signup',
    PRODUCT_BEST_SELLING: '/api/product/best-selling',
    PRODUCT_FREE_DELIVERY: '/api/product/free-delivery',
    PRODUCT_SUPER_DEALS: '/api/product/super-deals',
    PRODUCT_TOP_OF_WEEK: '/api/product/top-of-week',
    FAVORITS: '/api/favorites',
    CART: '/api/cart',
    PRODUCT_VIEW: '/api/views',
    USER: '/api/user',
    USER_UPDATE_PASSWORD: '/api/user/update-password',
    VOUCHERS: '/api/voucher',
    ALL_CATEGORIES: '/api/category/get-all',
    ALL_SUB_CATEGORIES: '/api/sub-categories/get-all',
}
