const dummy_products = [
  {
    id: "1",
    name: "Product A",
    price: 499,
    oldPrice: 599,
    onSale: false,
    availability: true,
    quantity: 10,
    image: "https://picsum.photos/150?random=1",
    category: "Electronics",
    isFavorite: true,
    rating: 8,
  },
  {
    id: "2",
    name: "Product B",
    price: 799,
    oldPrice: 899,
    onSale: false,
    availability: false,
    quantity: 3,
    image: "https://picsum.photos/150?random=2",
    category: "Home Appliances",
    isFavorite: true,
    rating: 5,
  },
  {
    id: "3",
    name: "Product C",
    price: 299,
    oldPrice: null,
    onSale: false,
    availability: true,
    quantity: 20,
    image: "https://picsum.photos/150?random=3",
    isFavorite: false,
    category: "Books",
    rating: 7,
  },
  {
    id: "4",
    name: "Product D",
    price: 1299,
    oldPrice: 1499,
    onSale: true,
    availability: true,
    quantity: 5,
    image: "https://picsum.photos/150?random=4",
    isFavorite: false,
    category: "Clothing",
    rating: 10,
  },
  {
    id: "5",
    name: "Product E",
    price: 999,
    oldPrice: 1099,
    onSale: false,
    availability: true,
    quantity: 15,
    image: "https://picsum.photos/150?random=5",
    isFavorite: false,
    category: "Sports",
    rating: 9,
  },
  {
    id: "6",
    name: "Product F",
    price: 1499,
    oldPrice: 1599,
    onSale: true,
    availability: true,
    quantity: 7,
    image: "https://picsum.photos/150?random=6",
    isFavorite: true,
    category: "Toys",
    rating: 8,
  },
  {
    id: "7",
    name: "Product G",
    price: 349,
    oldPrice: 399,
    onSale: true,
    availability: false,
    quantity: 1,
    image: "https://picsum.photos/150?random=7",
    isFavorite: true,
    category: "Stationery",
    rating: 0,
  },
  {
    id: "8",
    name: "Product H",
    price: 599,
    oldPrice: null,
    onSale: false,
    availability: true,
    quantity: 12,
    image: "https://picsum.photos/150?random=8",
    isFavorite: false,
    category: "Accessories",
    rating: 1,
  },
  {
    id: "9",
    name: "Product I",
    price: 799,
    oldPrice: 899,
    onSale: false,
    availability: true,
    quantity: 8,
    image: "https://picsum.photos/150?random=9",
    isFavorite: true,
    category: "Beauty",
    rating: 3,
  },
  {
    id: "10",
    name: "Product J",
    price: 499,
    oldPrice: 599,
    onSale: false,
    availability: false,
    quantity: 4,
    image: "https://picsum.photos/150?random=10",
    isFavorite: false,
    category: "Electronics",
    rating: 2,
  },
  {
    id: "11",
    name: "Product K",
    price: 699,
    oldPrice: null,
    onSale: false,
    availability: true,
    quantity: 9,
    image: "https://picsum.photos/150?random=11",
    isFavorite: true,
    category: "Clothing",
    rating: 6,
  },
  {
    id: "12",
    name: "Product L",
    price: 999,
    oldPrice: 1099,
    onSale: true,
    availability: true,
    quantity: 6,
    image: "https://picsum.photos/150?random=12",
    isFavorite: false,
    category: "Sports",
    rating: 7,
  },
  {
    id: "13",
    name: "Product M",
    price: 1199,
    oldPrice: 1299,
    onSale: true,
    availability: true,
    quantity: 10,
    image: "https://picsum.photos/150?random=13",
    isFavorite: true,
    category: "Home Appliances",
    rating: 7,
  },
  {
    id: "14",
    name: "Product N",
    price: 799,
    oldPrice: null,
    onSale: false,
    availability: true,
    quantity: 3,
    image: "https://picsum.photos/150?random=14",
    isFavorite: false,
    category: "Toys",
    rating: 10,
  },
  {
    id: "15",
    name: "Product O",
    price: 1299,
    oldPrice: 1399,
    onSale: true,
    availability: true,
    quantity: 5,
    image: "https://picsum.photos/150?random=15",
    isFavorite: true,
    category: "Books",
    rating: 9,
  },
  {
    id: "17",
    name: "Product Q",
    price: 659,
    availability: false,
    oldPrice: 899,
    onSale: true,
    quantity: 5,
    image: "https://picsum.photos/150?random=17",
    isFavorite: true,
    category: "Gardening",
    rating: 8,
  },
  {
    id: "18",
    name: "Product R",
    price: 459,
    availability: true,
    oldPrice: 699,
    onSale: false,
    quantity: 3,
    image: "https://picsum.photos/150?random=18",
    isFavorite: false,
    category: "Kitchen",
    rating: 6,
  },
  {
    id: "19",
    name: "Product S",
    price: 1299,
    availability: true,
    oldPrice: 1399,
    onSale: true,
    quantity: 8,
    image: "https://picsum.photos/150?random=19",
    isFavorite: true,
    category: "Toys",
    rating: 3,
  },
  {
    id: "20",
    name: "Product T",
    price: 999,
    availability: false,
    oldPrice: 1399,
    onSale: false,
    quantity: 7,
    image: "https://picsum.photos/150?random=20",
    isFavorite: false,
    category: "Sports",
    rating: 5,
  },
];

export default dummy_products;
