import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider, theme } from "antd";
import AntdStyledComponentsRegistry from "./AntdComponentRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <AntdStyledComponentsRegistry>{children}</AntdStyledComponentsRegistry>
      </body>
    </html>
  );
}
