-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "freebieProductIDs" INTEGER[],
ADD COLUMN     "relatedProductIDs" INTEGER[],
ALTER COLUMN "currency" DROP NOT NULL,
ALTER COLUMN "isFeatured" DROP NOT NULL,
ALTER COLUMN "rating" DROP NOT NULL,
ALTER COLUMN "rating" SET DEFAULT 4.9,
ALTER COLUMN "brand" DROP NOT NULL,
ALTER COLUMN "score" DROP NOT NULL,
ALTER COLUMN "score" SET DEFAULT 0.7;
